[[constraint]]
  branch = "master"
  name = "github.com/VividCortex/siesta"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  name = "github.com/go-martini/martini"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-zoo/bone"
  version = "1.2.0"

[[constraint]]
  name = "github.com/gocraft/web"
  version = "1.1.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.0"

[[constraint]]
  name = "github.com/guregu/kami"
  version = "2.2.1"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.2.6"

[[constraint]]
  name = "github.com/pressly/chi"
  version = "3.3.2"

[[constraint]]
  name = "github.com/zenazn/goji"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/zpatrick/fireball"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"
